#! /bin/bash

source ~/.envs/data-golem/bin/activate
export YAGNA_APPKEY=6aedce461af045b8a69de2189c5e3d51

docker build -t dicom-golem:latest .
gvmkit-build dicom-golem:latest
var=$(gvmkit-build dicom-golem:latest --push | tee /dev/tty)
echo $var | grep -o 'hash link.*' | cut -f3 -d' ' > hash_link
rm docker*
